package fr.diginamic.hello.controllers;

import fr.diginamic.hello.services.HelloService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/hello")
public class HelloControleur {
    private final HelloService helloService;

    /**
     * Constructor for the controller, injecting the HelloService.
     *
     * @param helloService the service used to generate greetings.
     */
    @Autowired
    public HelloControleur(HelloService helloService) {
        this.helloService = helloService;
    }

    /**
     * HTTP GET endpoint that returns a greeting.
     *
     * @return a string containing the greeting generated by the {@link HelloService}.
     */
    @GetMapping
    public String sayHello() {
        return helloService.salutations();
    }
}
